name: build-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_HUB_ORGANISATION: rtgsglobal
  SOLUTION_FOLDER: src/RTGS.IDCrypt.Service

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dotnet Tool Manifest
        run: dotnet new tool-manifest
      - name: Install dotnet format
        run: dotnet tool install dotnet-format
      - name: dotnet Format
        run: dotnet format ${{env.SOLUTION_FOLDER}} --verify-no-changes
      - name: Run Azurite Table Storage
        run: docker run --name azurite -d -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build & run tests
        run: docker build ${{env.SOLUTION_FOLDER}} --target build --network=host
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite
  publish-to-docker:
    name: publish-to-docker
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    env:
      DOCKER_HUB_REPO: idcrypt-service-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run Azurite Table Storage
        run: docker run --name azurite -d -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ${{env.SOLUTION_FOLDER}}
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
          network: host
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite
  trigger-devops-pipeline:
    name: trigger-devops-pipeline
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: publish-to-docker
    steps:
      - name: Azure Pipelines Action
        # The following does need to be 1.2 (or later) otherwise the azure-pipeline-variables are not passed to the pipeline.
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: ${{ secrets.AZURE_DEVOPS_IDCRYPT_SERVICE_DEPLOYMENT_PIPELINE }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables: '{"IdCryptServiceVersion": "${{ github.run_number }}"}'
  publish-to-docker-release:
    name: publish-to-docker-release
    if: github.event_name == 'release'
    needs: build
    env:
      DOCKER_HUB_REPO: idcrypt-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run Azurite Table Storage
        run: docker run --name azurite -d -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ${{env.SOLUTION_FOLDER}}
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
          network: host
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite