name: build-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_HUB_ORGANISATION: rtgsglobal

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Azurite Table Storage
        run: docker run --name azurite -d -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build & run tests
        run: docker build src/RTGS.IDCrypt.Service --target build --network=host
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite
  publish-to-docker-dev:
    name: publish-to-docker-dev
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    env:
      DOCKER_HUB_REPO: rtgs-idcrypt-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run Azurite Table Storage
        run: docker run --name azurite -d -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: src/RTGS.IDCrypt.Service
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite
