name: build-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Azurite Table Storage
        run: docker run --name azurite -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002
      - name: Build & run tests
        run: docker build src/RTGS.IDCrypt.Service --target build --network=host
      - name: Remove Azurite Table Storage
        run: docker rm -f azurite
